server:
  port: ${port:8090}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    password: root
    username: root
  application:
    name: user-service
mybatis:
  type-aliases-package: com.chen.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
